name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
       node-version: '14.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install -U pip jupyterlab~=3.0 jupyter-packaging~=0.7.9
    - name: Build the extension
      run: |
        jlpm
        jlpm run eslint:check
        jlpm run prettier:check

        python -m pip install .

        jupyter labextension list 1>labextensions 2>&1
        cat labextensions | grep "jupyterlab-interactive-dashboard-editor.*OK"

        python -m jupyterlab.browser_check

